version: "3.7"

services:

 electric_multivariate:
  image: electric
  volumes:
   - ./:/app/
  stdin_open: true
  tty: true
  deploy:
   resources:
    reservations:
     devices:
      - capabilities: [gpu]
