version: "3.7"

services:

 electric_{name_service}:
  image: electric
  volumes:
   - ~/{path_to_folder}/:/app/
  stdin_open: true
  tty: true
  deploy:
   resources:
    reservations:
     devices:
      - capabilities: [gpu]
